@OrderAPIDemoProject_HostAddress = http://localhost:5112
###
GET {{OrderAPIDemoProject_HostAddress}}/api/Order

###
GET {{OrderAPIDemoProject_HostAddress}}/api/Order/1
Accept: application/json

###
POST {{OrderAPIDemoProject_HostAddress}}/api/Order
Content-Type: application/json
{
  "customerEmail": "a@b.com",
  "productCode": "001",
  "quantity": 50,
}